# RFlect Default Report Template
# This template defines the structure and content of generated reports.

name: "Standard Antenna Test Report"
version: "1.0"

# Report metadata
metadata:
  title: "Antenna Radiation Pattern Test Report"
  subtitle: "Passive/Active Measurement Results"
  confidentiality: "Company Confidential"

# Sections to include (in order)
sections:
  - id: cover_page
    title: "Cover Page"
    enabled: true
    content:
      - logo  # From config branding
      - title
      - subtitle
      - date
      - confidentiality_notice

  - id: table_of_contents
    title: "Table of Contents"
    enabled: true
    auto_generate: true

  - id: executive_summary
    title: "Executive Summary"
    enabled: true
    ai_generated: true
    ai_prompt: |
      You are an RF engineer writing an executive summary for an antenna test report.
      Based on the measurement data, write a concise 2-3 paragraph summary that:
      1. States the antenna under test and frequency range
      2. Highlights key performance metrics (max gain, pattern type, beamwidth)
      3. Notes any concerns or notable characteristics
      4. Provides an overall assessment (meets specs, needs improvement, etc.)

      Keep the tone professional and technical but accessible.

  - id: test_configuration
    title: "Test Configuration"
    enabled: true
    content:
      - antenna_description
      - test_equipment
      - test_conditions
      - frequency_list
      - measurement_parameters

  - id: gain_summary
    title: "Gain Summary"
    enabled: true
    content:
      - gain_table  # Frequency vs Max Gain table
      - gain_chart  # Optional bar chart
    ai_analysis: true
    ai_prompt: |
      Analyze the gain data and comment on:
      - Gain stability across the frequency band
      - Peak gain frequency
      - Any anomalies or unexpected variations

  - id: radiation_patterns
    title: "Radiation Patterns"
    enabled: true
    subsections:
      - id: 2d_patterns
        title: "2D Pattern Cuts"
        enabled: true
        plots:
          - azimuth_cut  # Phi sweep at theta=90
          - elevation_cut  # Theta sweep at phi=0
        per_frequency: true
        polarizations: ["total"]  # Can include hpol, vpol

      - id: 3d_patterns
        title: "3D Radiation Patterns"
        enabled: false  # Disabled by default (large)
        plots:
          - 3d_surface
        per_frequency: true

      - id: polar_patterns
        title: "Polar Radiation Patterns"
        enabled: true
        plots:
          - polar_azimuth
          - polar_elevation
        per_frequency: true

  - id: pattern_analysis
    title: "Pattern Analysis"
    enabled: true
    content:
      - pattern_type
      - hpbw_table  # Half-power beamwidth per frequency
      - front_to_back_ratio
      - null_locations
      - sidelobe_levels
    ai_analysis: true
    ai_prompt: |
      Analyze the radiation patterns and comment on:
      - Pattern classification (directional, omnidirectional, etc.)
      - Beamwidth characteristics and suitability for application
      - Front-to-back ratio implications
      - Any pattern asymmetries or anomalies

  - id: polarization_analysis
    title: "Polarization Analysis"
    enabled: true
    content:
      - dominant_polarization
      - xpd_table  # Cross-polar discrimination
      - polarization_balance
    ai_analysis: true

  - id: recommendations
    title: "Conclusions and Recommendations"
    enabled: true
    ai_generated: true
    ai_prompt: |
      Based on all the measurement data, provide:
      1. Summary of antenna performance vs typical specifications
      2. Identified strengths of the design
      3. Areas for potential improvement
      4. Recommendations for specific applications
      5. Any suggested follow-up testing

      Be specific and actionable in recommendations.

  - id: appendix_data
    title: "Appendix: Raw Data"
    enabled: false  # Disabled by default (lengthy)
    content:
      - full_data_tables
      - measurement_uncertainty

# Output settings
output:
  format: "docx"
  page_size: "letter"  # letter, a4
  orientation: "portrait"
  margins:
    top: 1.0
    bottom: 1.0
    left: 1.25
    right: 1.25

# Branding (can be overridden by config_local.py)
branding:
  logo: null  # Path or null for RFlect default
  company_name: null  # From config
  header_text: null
  footer_text: "Generated by RFlect v4.0.0"
  colors:
    primary: "#1a5276"
    secondary: "#2874a6"
    accent: "#3498db"

# AI settings
ai:
  model: "gpt-4o-mini"
  temperature: 0.7
  max_tokens_per_section: 500
  include_technical_details: true
  formality: "professional"  # professional, technical, casual
