"""
RFlect Configuration Template

This is the default configuration file that is tracked in git.
DO NOT edit this file directly for company-specific branding.

To customize for your company:
1. Copy this file to 'config_local.py'
2. Edit config_local.py with your settings
3. config_local.py will automatically override these defaults
4. config_local.py is in .gitignore and won't be committed

This template provides neutral/generic branding by default.
"""

# ============================================================================
# PLOTTING CONFIGURATION
# ============================================================================

interpolate_3d_plots = True  # Default value, can be set to False to disable interpolation

# 3D Plotting Interpolation Resolution for viewing plots (lower for better performance)
PHI_RESOLUTION = 120  # default 360 = 1deg spacing
THETA_RESOLUTION = 60  # default 180 - 1deg spacing

# 3D Plotting Interpolation Resolution for Saving plots (higher for better resolution in documentation)
PHI_RESOLUTION_Save = 360  # default 360 = 1deg spacing
THETA_RESOLUTION_Save = 180  # default 180 - 1deg spacing

# Set Min/Max for optional 2D polar plots on passive scans
polar_dB_max = 5.0
polar_dB_min = -20.0

# Maritime / Horizon Plot Defaults
MARITIME_PLOTS_ENABLED = False
HORIZON_THETA_MIN = 60.0
HORIZON_THETA_MAX = 120.0
HORIZON_THETA_CUTS = [60, 70, 80, 90, 100, 110, 120]
HORIZON_COVERAGE_THRESHOLD = -3.0  # dB below peak for coverage calculation

# ============================================================================
# GUI SETTINGS
# ============================================================================

# GUI Colors
DARK_BG_COLOR = "#2E2E2E"
LIGHT_TEXT_COLOR = "#FFFFFF"
ACCENT_BLUE_COLOR = "#4A90E2"
BUTTON_COLOR = "#3A3A3A"
HOVER_COLOR = "#4A4A4A"
ACCENT_GREEN_COLOR = "#4CAF50"

# Status/Feedback Colors
ERROR_COLOR = "#F44336"
WARNING_COLOR = "#FFC107"
SUCCESS_COLOR = "#4CAF50"
INFO_COLOR = "#4A90E2"

# GUI Fonts
HEADER_FONT = ("Arial", 14, "bold")
LABEL_FONT = ("Arial", 12)
FONT_SM = ("Arial", 9)
FONT_MD = ("Arial", 11)
FONT_LG = ("Arial", 13)
FONT_XL = ("Arial", 16, "bold")

# Spacing Constants
PAD_SM = 5
PAD_MD = 10
PAD_LG = 20

# Extended Dark Palette
SURFACE_COLOR = "#353535"
SURFACE_LIGHT_COLOR = "#404040"
BORDER_COLOR = "#505050"
DIVIDER_COLOR = "#444444"
LOG_BG_COLOR = "#1E1E1E"
HEADER_BAR_COLOR = "#252525"
HEADER_ACCENT_COLOR = "#E63946"
DISABLED_FG_COLOR = "#A0A0A0"  # WCAG AA compliant (5.6:1 on #2E2E2E)
FOCUS_BORDER_COLOR = "#5A9CF5"

# Modern Fonts (platform-aware fallbacks for Linux/macOS/Windows)
import sys as _sys

if _sys.platform == "win32":
    FONT_FAMILY = "Segoe UI"
    _MONO_FAMILY = "Consolas"
elif _sys.platform == "darwin":
    FONT_FAMILY = "Helvetica Neue"
    _MONO_FAMILY = "Menlo"
else:  # Linux / other
    FONT_FAMILY = "DejaVu Sans"
    _MONO_FAMILY = "DejaVu Sans Mono"

HEADER_BAR_FONT = (FONT_FAMILY, 16, "bold")
HEADER_VERSION_FONT = (FONT_FAMILY, 9)
SECTION_HEADER_FONT = (FONT_FAMILY, 11, "bold")
LABEL_FONT_MODERN = (FONT_FAMILY, 10)
BUTTON_FONT = (FONT_FAMILY, 10)
LOG_FONT = (_MONO_FAMILY, 9)
STATUS_FONT = (FONT_FAMILY, 9)

# Button Geometry
BTN_PADX = 16
BTN_PADY = 6

# Section Spacing
SECTION_PAD = 12
WIDGET_GAP = 8

# ============================================================================
# REPORT BRANDING CONFIGURATION (DEFAULT: Generic/Neutral)
# ============================================================================
# These are neutral defaults. Create config_local.py to customize.

# Company/Brand Name
BRAND_NAME = None  # No specific branding by default

# Brand Colors (RGB tuples: (Red, Green, Blue) with values 0-255)
# Neutral gray/blue color scheme
BRAND_PRIMARY_COLOR = (70, 130, 180)  # Steel Blue
BRAND_DARK_COLOR = (50, 50, 50)  # Dark Gray
BRAND_LIGHT_COLOR = (128, 128, 128)  # Medium Gray

# Logo Configuration
LOGO_FILENAME = None  # No logo by default
LOGO_WIDTH_INCHES = 2.0  # Width of logo in report header
LOGO_ALIGNMENT = "LEFT"  # "LEFT", "CENTER", or "RIGHT"

# Report Footer
BRAND_TAGLINE = None  # No tagline by default
BRAND_WEBSITE = None  # No website by default

# Report Styling
REPORT_SUBTITLE = "Antenna Measurement & Analysis Report"
TITLE_FONT_SIZE = 28  # Title page font size in points
SUBTITLE_FONT_SIZE = 14  # Subtitle font size in points
HEADING1_FONT_SIZE = 18  # Section heading font size
HEADING2_FONT_SIZE = 14  # Subsection heading font size

# ============================================================================
# AI PROVIDER CONFIGURATION
# ============================================================================

# AI Provider: "openai", "anthropic", or "ollama"
AI_PROVIDER = "openai"

# Provider-specific model defaults
AI_OPENAI_MODEL = "gpt-4o-mini"
AI_ANTHROPIC_MODEL = "claude-sonnet-4-20250514"
AI_OLLAMA_MODEL = "llama3.1"
AI_OLLAMA_URL = "http://localhost:11434"

# Vision model override (for plot analysis)
# Set to a vision-capable model if your default model doesn't support vision
AI_VISION_MODEL = None  # None = use same as AI_MODEL. e.g. "llava" for Ollama

# ============================================================================
# AI ANALYSIS CONFIGURATION (OpenAI)
# ============================================================================

# AI Model Settings
AI_MODEL = "gpt-4o-mini"  # OpenAI model to use (default: gpt-4o-mini for compatibility)
#
# RECOMMENDED MODELS FOR AI CHAT (with function calling):
#
# GPT-5.2 FAMILY (LATEST - Uses Responses API):
# - "gpt-5.2" - Flagship model, best quality, supports tools + vision
# - "gpt-5-mini" ⭐ RECOMMENDED - Great balance of speed/cost/quality
# - "gpt-5-nano" - Fastest, lowest cost, good for simple analysis
#
# GPT-4 FAMILY (LEGACY - Uses Chat Completions API):
# - "gpt-4o-mini" - Best legacy value, fast, supports functions + vision
# - "gpt-4o" - Premium quality, supports functions + vision
# - "chatgpt-4o-latest" - Latest 4o version
#
# ❌ NOT COMPATIBLE WITH AI CHAT:
# - "o1-preview", "o1-mini", "o3-mini" - NO function calling support
#   These models cannot call Python functions interactively
#
# GPT-5.2 ADVANTAGES:
# ✅ Uses new Responses API with reasoning control
# ✅ Supports tools (function calling) with strict schemas
# ✅ Supports vision (image analysis for plots)
# ✅ Configurable reasoning effort (none/low/medium/high)
# ✅ Configurable text verbosity (low/medium/high)
# ✅ Better structured output support
#
# WHEN TO USE ALTERNATIVES:
# - Use "gpt-5.2" for best quality analysis
# - Use "gpt-5-mini" for balanced speed/quality
# - Use "gpt-4o-mini" if GPT-5 API access not available
# - DON'T use O-series models for AI chat (no function calling)
AI_MAX_TOKENS = 150  # Maximum response length for report captions (150 = ~100 words)
AI_CHAT_MAX_TOKENS = 800  # Maximum response length for AI Chat assistant (800 = ~500 words)
# NOTE: For GPT-5, this maps to verbosity levels:
# ≤100 → "low", ≤250 → "medium", >250 → "high"
AI_TEMPERATURE = 0.2  # Lower = more consistent (0.0-1.0)
# NOTE: GPT-4 uses this directly. GPT-5 maps it to reasoning.effort:
# ≤0.1 → "none", ≤0.3 → "low", ≤0.6 → "medium", >0.6 → "high"
AI_TOP_P = 0.8  # Nucleus sampling parameter (GPT-4 only, not used for GPT-5)
AI_TIMEOUT_SECONDS = 30  # API request timeout

# AI Prompt Settings
AI_RESPONSE_STYLE = "concise"  # "concise" or "detailed"
# - "concise": Single-paragraph technical descriptions (~80 words)
# - "detailed": Multi-section analysis with recommendations (~200+ words)
AI_INCLUDE_RECOMMENDATIONS = False  # Include design recommendations in each caption
# Set True for educational reports, False for concise documentation
AI_MAX_WORDS = 80  # Target word count for AI responses
# Suggested ranges: 60-80 (concise), 150-250 (detailed), 300+ (research-level)

# Advanced AI Parameters (GPT-5.2 Responses API)
# These parameters are ONLY used when AI_MODEL is a GPT-5 variant (gpt-5*, gpt-5.2)
# For GPT-4 models, these are ignored and Chat Completions API parameters (temperature, top_p) are used instead

AI_REASONING_EFFORT = "low"  # GPT-5.2 reasoning intensity: "none", "low", "medium", "high", "xhigh"
# - "none": No reasoning tokens, fastest response (like GPT-4 behavior)
# - "low": Light reasoning for straightforward technical analysis (RECOMMENDED for RF reports)
# - "medium": Balanced reasoning for complex patterns
# - "high": Deep reasoning for research-level analysis (slower, more expensive)
# - "xhigh": Maximum reasoning effort for most complex problems
# NOTE: RF antenna analysis is domain-specific but not highly complex reasoning,
# so "low" provides best speed/quality/cost balance

AI_TEXT_VERBOSITY = "auto"  # GPT-5.2 output verbosity: "auto", "low", "medium", "high"
# - "auto": Let model decide based on AI_MAX_TOKENS (RECOMMENDED)
# - "low": Terse, minimal prose (good for captions)
# - "medium": Balanced detail (good for technical reports)
# - "high": Comprehensive explanations (research papers)
# When "auto", maps AI_MAX_TOKENS: ≤100→low, ≤250→medium, >250→high

AI_GENERATE_REASONING_SUMMARY = False  # GPT-5.2 only: Include reasoning summary in response
# When True, provides insight into model's thought process
# Useful for debugging or understanding complex analysis decisions
# Adds ~50-100 tokens to response, minimal cost impact

AI_USE_STRUCTURED_OUTPUT = False  # Enable JSON structured output for consistent formatting
# When True, enforces schema-based responses (requires schema definition in code)
# Useful for programmatic parsing but reduces natural language quality
# RECOMMENDED: Keep False for readable report captions

# ============================================================================
# LINK BUDGET / RANGE ESTIMATION
# ============================================================================
# Integrates measured antenna gain with Friis / log-distance path loss to
# compute maximum communication range per azimuth direction.

LINK_BUDGET_ENABLED = False
LINK_BUDGET_PROTOCOL_PRESET = "BLE 1Mbps"  # "Custom", "BLE 1Mbps", "BLE 2Mbps",
# "BLE Long Range (Coded)", "WiFi 802.11n (MCS0)", "WiFi 802.11ac (MCS0)",
# "Zigbee / Thread", "LoRa SF12", "LoRa SF7", "LTE Cat-M1", "NB-IoT"
LINK_BUDGET_TX_POWER_DBM = 0.0            # Transmit power in dBm
LINK_BUDGET_RX_SENSITIVITY_DBM = -98.0    # Receiver sensitivity in dBm
LINK_BUDGET_RX_GAIN_DBI = 0.0            # Receive antenna gain in dBi
LINK_BUDGET_PATH_LOSS_EXP = 2.0          # Path loss exponent (2=free-space, 3=indoor, 4=worst)
LINK_BUDGET_MISC_LOSS_DB = 10.0          # Cable, mismatch, body loss, etc. in dB
LINK_BUDGET_TARGET_RANGE_M = 5.0         # Target range for reverse calculations in metres

# ============================================================================
# INDOOR PROPAGATION ANALYSIS
# ============================================================================
# Models indoor propagation effects (ITU-R P.1238) on measured antenna patterns
# including wall penetration (ITU-R P.2040) and shadow fading.

INDOOR_ANALYSIS_ENABLED = False
INDOOR_ENVIRONMENT = "Office"             # "Free Space", "Office", "Residential", "Commercial",
# "Hospital", "Industrial", "Outdoor Urban", "Outdoor LOS"
INDOOR_PATH_LOSS_EXP = 3.0               # Overridable, auto-set by environment preset
INDOOR_NUM_WALLS = 1                      # Number of wall obstructions
INDOOR_WALL_MATERIAL = "drywall"          # drywall, wood, glass, brick, concrete, metal
INDOOR_SHADOW_FADING_DB = 5.0            # Log-normal shadow fading std deviation (dB)
INDOOR_MAX_DISTANCE_M = 30.0             # Max range for coverage plots (metres)

# ============================================================================
# MULTIPATH FADING ANALYSIS
# ============================================================================
# Statistical fading models to assess reliability of the measured antenna
# performance in multipath environments.

FADING_ANALYSIS_ENABLED = False
FADING_MODEL = "rayleigh"                 # "rayleigh" (NLOS) or "rician" (LOS)
FADING_RICIAN_K = 10                      # Rician K-factor (linear, LOS/scattered ratio)
FADING_TARGET_RELIABILITY = 99.0         # Target reliability percentage for fade margin
FADING_REALIZATIONS = 1000                # Monte-Carlo fading realizations

# ============================================================================
# MIMO / DIVERSITY ANALYSIS
# ============================================================================
# Enhanced MIMO analysis with capacity curves, combining techniques,
# and pattern-based metrics. Requires ECC analysis to be enabled.

MIMO_ANALYSIS_ENABLED = False
MIMO_SNR_DB = 20                          # Operating SNR for capacity analysis (dB)
MIMO_SNR_RANGE_DB = (-5, 30)             # SNR range for capacity-vs-SNR curves
MIMO_FADING_MODEL = "rayleigh"           # "rayleigh" or "rician" for capacity simulation
MIMO_RICIAN_K = 10                        # K-factor for Rician MIMO channels
MIMO_XPR_DB = 6.0                        # Cross-polarization ratio (indoor ~6 dB)

# ============================================================================
# WEARABLE / MEDICAL DEVICE ANALYSIS
# ============================================================================
# Body-worn performance analysis across multiple positions,
# dense device interference modeling, and SAR screening.

WEARABLE_ANALYSIS_ENABLED = False
WEARABLE_BODY_POSITIONS = ["wrist", "chest", "hip", "head"]
WEARABLE_TX_POWER_MW = 1.0               # Transmit power in milliwatts
WEARABLE_DENSE_DEVICE_COUNT = 20          # Number of nearby co-channel devices
WEARABLE_ROOM_SIZE_M = (10, 10, 3)       # Room dimensions (L, W, H) in metres
