"""
Configuration file for the RFlect application.

This module loads default settings from config_template.py and then
applies user-specific overrides from config_local.py (if it exists).

DO NOT edit this file for branding changes.
Create/edit config_local.py instead (see config_template.py for examples).
"""

# Load default configuration from template
from config_template import *  # type: ignore[misc]  # noqa: F403

# Try to load local overrides (company-specific branding)
# config_local.py is in .gitignore and won't be committed
try:
    from config_local import *  # type: ignore[assignment,misc]  # noqa: F403

    print("[OK] Loaded custom branding from config_local.py")
except ImportError:
    print("[INFO] Using default branding (create config_local.py to customize)")
    pass
