"""
RFlect Configuration Template

This is the default configuration file that is tracked in git.
DO NOT edit this file directly for company-specific branding.

To customize for your company:
1. Copy this file to 'config_local.py'
2. Edit config_local.py with your settings
3. config_local.py will automatically override these defaults
4. config_local.py is in .gitignore and won't be committed

This template provides neutral/generic branding by default.
"""

# ============================================================================
# PLOTTING CONFIGURATION
# ============================================================================

interpolate_3d_plots = True  # Default value, can be set to False to disable interpolation

# 3D Axis Scaling — per plot type (auto | manual)
AXIS_SCALE_MODE_TOTAL = "auto"
AXIS_MIN_TOTAL = -20.0
AXIS_MAX_TOTAL = 10.0
AXIS_SCALE_MODE_HPOL = "auto"
AXIS_MIN_HPOL = -25.0
AXIS_MAX_HPOL = 5.0
AXIS_SCALE_MODE_VPOL = "auto"
AXIS_MIN_VPOL = -25.0
AXIS_MAX_VPOL = 10.0

# 3D Plotting Interpolation Resolution for viewing plots (lower for better performance)
PHI_RESOLUTION = 120  # default 360 = 1deg spacing
THETA_RESOLUTION = 60  # default 180 - 1deg spacing

# 3D Plotting Interpolation Resolution for Saving plots (higher for better resolution in documentation)
PHI_RESOLUTION_Save = 360  # default 360 = 1deg spacing
THETA_RESOLUTION_Save = 180  # default 180 - 1deg spacing

# Set Min/Max for optional 2D polar plots on passive scans
polar_dB_max = 5.0
polar_dB_min = -20.0

# Maritime / Horizon Plot Defaults
MARITIME_PLOTS_ENABLED = False
HORIZON_THETA_MIN = 60.0
HORIZON_THETA_MAX = 120.0
HORIZON_THETA_CUTS = [60, 70, 80, 90, 100, 110, 120]
HORIZON_COVERAGE_THRESHOLD = -3.0  # dB below peak for coverage calculation
CONDUCTED_POWER_DBM = None  # Optional: conducted power in dBm for efficiency calculation

# ============================================================================
# GUI SETTINGS
# ============================================================================

# GUI Colors
DARK_BG_COLOR = "#2E2E2E"
LIGHT_TEXT_COLOR = "#FFFFFF"
ACCENT_BLUE_COLOR = "#4A90E2"
BUTTON_COLOR = "#3A3A3A"
HOVER_COLOR = "#4A4A4A"
ACCENT_GREEN_COLOR = "#4CAF50"

# Status/Feedback Colors
ERROR_COLOR = "#F44336"
WARNING_COLOR = "#FFC107"
SUCCESS_COLOR = "#4CAF50"
INFO_COLOR = "#4A90E2"

# Platform-aware font family (Linux/macOS/Windows) — defined first so every
# font constant below uses a family that actually exists on the host. "Arial"
# is not guaranteed on Linux and caused Tk substitution / misaligned dialogs.
import sys as _sys

if _sys.platform == "win32":
    FONT_FAMILY = "Segoe UI"
    _MONO_FAMILY = "Consolas"
elif _sys.platform == "darwin":
    FONT_FAMILY = "Helvetica Neue"
    _MONO_FAMILY = "Menlo"
else:  # Linux / other
    FONT_FAMILY = "DejaVu Sans"
    _MONO_FAMILY = "DejaVu Sans Mono"

# GUI Fonts (now cross-platform via FONT_FAMILY)
HEADER_FONT = (FONT_FAMILY, 14, "bold")
LABEL_FONT = (FONT_FAMILY, 12)
FONT_SM = (FONT_FAMILY, 9)
FONT_MD = (FONT_FAMILY, 11)
FONT_LG = (FONT_FAMILY, 13)
FONT_XL = (FONT_FAMILY, 16, "bold")

# Spacing Constants
PAD_SM = 5
PAD_MD = 10
PAD_LG = 20

# Extended Dark Palette
SURFACE_COLOR = "#353535"
SURFACE_LIGHT_COLOR = "#404040"
BORDER_COLOR = "#505050"
DIVIDER_COLOR = "#444444"
LOG_BG_COLOR = "#1E1E1E"
HEADER_BAR_COLOR = "#252525"
HEADER_ACCENT_COLOR = "#E63946"
DISABLED_FG_COLOR = "#A0A0A0"  # WCAG AA compliant (5.6:1 on #2E2E2E)
FOCUS_BORDER_COLOR = "#5A9CF5"

# Modern Fonts (same platform-aware family)
HEADER_BAR_FONT = (FONT_FAMILY, 16, "bold")
HEADER_VERSION_FONT = (FONT_FAMILY, 9)
SECTION_HEADER_FONT = (FONT_FAMILY, 11, "bold")
LABEL_FONT_MODERN = (FONT_FAMILY, 10)
BUTTON_FONT = (FONT_FAMILY, 10)
LOG_FONT = (_MONO_FAMILY, 9)
STATUS_FONT = (FONT_FAMILY, 9)

# Button Geometry
BTN_PADX = 16
BTN_PADY = 6

# Section Spacing
SECTION_PAD = 12
WIDGET_GAP = 8

# ============================================================================
# REPORT BRANDING CONFIGURATION (DEFAULT: Generic/Neutral)
# ============================================================================
# These are neutral defaults. Create config_local.py to customize.

# Company/Brand Name
BRAND_NAME = None  # No specific branding by default

# Brand Colors (RGB tuples: (Red, Green, Blue) with values 0-255)
# Neutral gray/blue color scheme
BRAND_PRIMARY_COLOR = (70, 130, 180)  # Steel Blue
BRAND_DARK_COLOR = (50, 50, 50)  # Dark Gray
BRAND_LIGHT_COLOR = (128, 128, 128)  # Medium Gray

# Logo Configuration
LOGO_FILENAME = None  # No logo by default
LOGO_WIDTH_INCHES = 2.0  # Width of logo in report header
LOGO_ALIGNMENT = "LEFT"  # "LEFT", "CENTER", or "RIGHT"

# Report Footer
BRAND_TAGLINE = None  # No tagline by default
BRAND_WEBSITE = None  # No website by default

# Report Styling
REPORT_SUBTITLE = "Antenna Measurement & Analysis Report"
TITLE_FONT_SIZE = 28  # Title page font size in points
SUBTITLE_FONT_SIZE = 14  # Subtitle font size in points
HEADING1_FONT_SIZE = 18  # Section heading font size
HEADING2_FONT_SIZE = 14  # Subsection heading font size

# ============================================================================
# LINK BUDGET / RANGE ESTIMATION
# ============================================================================
# Integrates measured antenna gain with Friis / log-distance path loss to
# compute maximum communication range per azimuth direction.

LINK_BUDGET_ENABLED = False
LINK_BUDGET_PROTOCOL_PRESET = "BLE 1Mbps"  # "Custom", "BLE 1Mbps", "BLE 2Mbps",
# "BLE Long Range (Coded)", "WiFi 802.11n (MCS0)", "WiFi 802.11ac (MCS0)",
# "Zigbee / Thread", "LoRa SF12", "LoRa SF7", "LTE Cat-M1", "NB-IoT"
LINK_BUDGET_TX_POWER_DBM = 0.0  # Transmit power in dBm
LINK_BUDGET_RX_SENSITIVITY_DBM = -98.0  # Receiver sensitivity in dBm
LINK_BUDGET_RX_GAIN_DBI = 0.0  # Receive antenna gain in dBi
LINK_BUDGET_PATH_LOSS_EXP = 2.0  # Path loss exponent (2=free-space, 3=indoor, 4=worst)
LINK_BUDGET_MISC_LOSS_DB = 10.0  # Cable, mismatch, body loss, etc. in dB
LINK_BUDGET_TARGET_RANGE_M = 5.0  # Target range for reverse calculations in metres

# ============================================================================
# INDOOR PROPAGATION ANALYSIS
# ============================================================================
# Models indoor propagation effects (ITU-R P.1238) on measured antenna patterns
# including wall penetration (ITU-R P.2040) and shadow fading.

INDOOR_ANALYSIS_ENABLED = False
INDOOR_ENVIRONMENT = "Office"  # "Free Space", "Office", "Residential", "Commercial",
# "Hospital", "Industrial", "Outdoor Urban", "Outdoor LOS"
INDOOR_PATH_LOSS_EXP = 3.0  # Overridable, auto-set by environment preset
INDOOR_NUM_WALLS = 1  # Number of wall obstructions
INDOOR_WALL_MATERIAL = "drywall"  # drywall, wood, glass, brick, concrete, metal
INDOOR_SHADOW_FADING_DB = 5.0  # Log-normal shadow fading std deviation (dB)
INDOOR_MAX_DISTANCE_M = 30.0  # Max range for coverage plots (metres)

# ============================================================================
# MULTIPATH FADING ANALYSIS
# ============================================================================
# Statistical fading models to assess reliability of the measured antenna
# performance in multipath environments.

FADING_ANALYSIS_ENABLED = False
FADING_MODEL = "rayleigh"  # "rayleigh" (NLOS) or "rician" (LOS)
FADING_RICIAN_K = 10  # Rician K-factor (linear, LOS/scattered ratio)
FADING_TARGET_RELIABILITY = 99.0  # Target reliability percentage for fade margin
FADING_REALIZATIONS = 1000  # Monte-Carlo fading realizations

# ============================================================================
# MIMO / DIVERSITY ANALYSIS
# ============================================================================
# Enhanced MIMO analysis with capacity curves, combining techniques,
# and pattern-based metrics. Requires ECC analysis to be enabled.

MIMO_ANALYSIS_ENABLED = False
MIMO_SNR_DB = 20  # Operating SNR for capacity analysis (dB)
MIMO_SNR_RANGE_DB = (-5, 30)  # SNR range for capacity-vs-SNR curves
MIMO_FADING_MODEL = "rayleigh"  # "rayleigh" or "rician" for capacity simulation
MIMO_RICIAN_K = 10  # K-factor for Rician MIMO channels
MIMO_XPR_DB = 6.0  # Cross-polarization ratio (indoor ~6 dB)

# ============================================================================
# WEARABLE / MEDICAL DEVICE ANALYSIS
# ============================================================================
# Body-worn performance analysis across multiple positions,
# dense device interference modeling, and SAR screening.

WEARABLE_ANALYSIS_ENABLED = False
WEARABLE_BODY_POSITIONS = ["wrist", "chest", "hip", "head"]
WEARABLE_TX_POWER_MW = 1.0  # Transmit power in milliwatts
WEARABLE_DENSE_DEVICE_COUNT = 20  # Number of nearby co-channel devices
WEARABLE_ROOM_SIZE_M = (10, 10, 3)  # Room dimensions (L, W, H) in metres
